btrfs-progs: check/lowmem: detect and report mixed inline and regular extents properly
[BUG]
When lowmem mode check is executed on a filesystem with mixed inline and
regular extent, it reports the error as file extent gap:

  [4/7] checking fs roots
  ERROR: root 5 EXTENT_DATA[257 4096] gap exists, expected: EXTENT_DATA[257 707]
  ERROR: errors found in fs roots
  found 135168 bytes used, error(s) found

Not detecting the mixed extent types.

[CAUSE]
The offending fs has the following data extents:

        item 9 key (257 INODE_REF 256) itemoff 15703 itemsize 14
                index 2 namelen 4 name: file
        item 10 key (257 EXTENT_DATA 0) itemoff 14975 itemsize 728
                generation 7 type 0 (inline)
                inline extent data size 707 ram_bytes 707 compression 0 (none)
        item 11 key (257 EXTENT_DATA 4096) itemoff 14922 itemsize 53
                generation 7 type 2 (prealloc)
                prealloc data disk byte 102457344 nr 4096
                prealloc data offset 0 nr 4096

The mixed extent type error is obvious, but for inline extent,
check_file_extent_inline() will increase the extent_end by inline size.

However for such mixed case, the regular extent will only start
sectorsize, leaving lowmem check only to report a hole gap.

[FIX]
This patch will fix it by:
- Introduce @found_inline parameter to detect mixed extent types
- Increase @end by sectorsize for check_file_extent_inline()

Signed-off-by: Qu Wenruo <wqu@suse.com>