btrfs-progs: mkfs: follow sectorsize for mixed mode
[BUG]
When running fstests with 4K sectorsize and 64K page size (aka subpage
support), the following tests failed:

  $ sudo ./check generic/416 generic/619
  FSTYP         -- btrfs
  PLATFORM      -- Linux/aarch64 rockpi4 5.12.0-rc8-custom+ #9 SMP Tue Apr 27 12:49:52 CST 2021
  MKFS_OPTIONS  -- -s 4k /dev/mapper/arm_nvme-scratch1
  MOUNT_OPTIONS -- /dev/mapper/arm_nvme-scratch1 /mnt/scratch

  generic/416     [failed, exit status 1]- output mismatch (see ~/xfstests-dev/results//generic/416.out.bad)
     QA output created by 416
    -wrote 16777216/16777216 bytes at offset 0
    -XXX Bytes, X ops; XX:XX:XX.X (XXX YYY/sec and XXX ops/sec)
    +mount: /mnt/scratch: wrong fs type, bad option, bad superblock on /dev/mapper/arm_nvme-scratch1, missing codepage or helper program, or other error.
    +mount failed
    +(see ~/xfstests-dev/results//generic/416.full for details)
    ...
    (Run 'diff -u ~/xfstests-dev/tests/generic/416.out ~/xfstests-dev/results//generic/416.out.bad'  to see the entire diff)
  generic/619     [failed, exit status 1]- output mismatch (see ~/xfstests-dev/results//generic/619.out.bad)
     QA output created by 619
    -Silence is golden
    +mount: /mnt/scratch: wrong fs type, bad option, bad superblock on /dev/mapper/arm_nvme-scratch1, missing codepage or helper program, or other error.
    +mount failed
    +(see ~/xfstests-dev/results//generic/619.full for details)
    ...
    (Run 'diff -u ~/xfstests-dev/tests/generic/619.out ~/xfstests-dev/results//generic/619.out.bad'  to see the entire diff)
  Ran: generic/416 generic/619
  Failures: generic/416 generic/619
  Failed 2 of 2 tests

[CAUSE]
Those two tests call _scratch_mkfs_sized to create a small fs, all of them
are smaller than the 256M.

Since the fs is small, fstests choose to pass -M to make a mixed btrfs.
(Let's just ignore whether we should pass -M here).

Then on 64K page size system, "mkfs.btrfs -s 4K -M -b 128M $dev" will fail
with the following error message:

  btrfs-progs v5.11
  See http://btrfs.wiki.kernel.org for more information.

  ERROR: illegal nodesize 65536 (not equal to 4096 for mixed block group)

This is caused by the nodesize selection, which always try to choose the
larger value between pagesize and sectorsize.

This hardcoded PAGESIZE usage in mkfs.btrfs makes us to choose 64K
nodesize even we specified to use 4K sectorsize.

[FIX]
Just use sectorsize as nodesize when -M is specified.

With this fix, above two tests now pass for btrfs subpage case.

Signed-off-by: Qu Wenruo <wqu@suse.com>